// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/book.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_proto_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_proto_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Publisher     string                 `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Year          string                 `protobuf:"bytes,5,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_proto_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_proto_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookResponse) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *BookResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

var File_proto_book_proto protoreflect.FileDescriptor

const file_proto_book_proto_rawDesc = "" +
	"\n" +
	"\x10proto/book.proto\x12\x05proto\"#\n" +
	"\vBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x90\x01\n" +
	"\fBookResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1c\n" +
	"\tpublisher\x18\x04 \x01(\tR\tpublisher\x12\x12\n" +
	"\x04year\x18\x05 \x01(\tR\x04year2\xfc\x01\n" +
	"\x04Book\x124\n" +
	"\agetBook\x12\x12.proto.BookRequest\x1a\x13.proto.BookResponse\"\x00\x128\n" +
	"\tlistBooks\x12\x12.proto.BookRequest\x1a\x13.proto.BookResponse\"\x000\x01\x12?\n" +
	"\x10getSpecifiedBook\x12\x12.proto.BookRequest\x1a\x13.proto.BookResponse\"\x00(\x01\x12C\n" +
	"\x12listSpecifiedBooks\x12\x12.proto.BookRequest\x1a\x13.proto.BookResponse\"\x00(\x010\x01B\x0fZ\r./proto;protob\x06proto3"

var (
	file_proto_book_proto_rawDescOnce sync.Once
	file_proto_book_proto_rawDescData []byte
)

func file_proto_book_proto_rawDescGZIP() []byte {
	file_proto_book_proto_rawDescOnce.Do(func() {
		file_proto_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_book_proto_rawDesc), len(file_proto_book_proto_rawDesc)))
	})
	return file_proto_book_proto_rawDescData
}

var file_proto_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_book_proto_goTypes = []any{
	(*BookRequest)(nil),  // 0: proto.BookRequest
	(*BookResponse)(nil), // 1: proto.BookResponse
}
var file_proto_book_proto_depIdxs = []int32{
	0, // 0: proto.Book.getBook:input_type -> proto.BookRequest
	0, // 1: proto.Book.listBooks:input_type -> proto.BookRequest
	0, // 2: proto.Book.getSpecifiedBook:input_type -> proto.BookRequest
	0, // 3: proto.Book.listSpecifiedBooks:input_type -> proto.BookRequest
	1, // 4: proto.Book.getBook:output_type -> proto.BookResponse
	1, // 5: proto.Book.listBooks:output_type -> proto.BookResponse
	1, // 6: proto.Book.getSpecifiedBook:output_type -> proto.BookResponse
	1, // 7: proto.Book.listSpecifiedBooks:output_type -> proto.BookResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_book_proto_init() }
func file_proto_book_proto_init() {
	if File_proto_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_book_proto_rawDesc), len(file_proto_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_book_proto_goTypes,
		DependencyIndexes: file_proto_book_proto_depIdxs,
		MessageInfos:      file_proto_book_proto_msgTypes,
	}.Build()
	File_proto_book_proto = out.File
	file_proto_book_proto_goTypes = nil
	file_proto_book_proto_depIdxs = nil
}
